server:
  port: 9620
lumber:
  filename: './logs/system.log'
  maxsize: 10
  maxbackups: 5
  maxage: 30
  compress: false
debugging:
  logger: false
database:
  dialect: mysql
  url: root:123@/databasetest?charset=utf8&parseTime=True&loc=Local
